DROP TABLE IF EXISTS "attachments" CASCADE;
DROP TABLE IF EXISTS "submission_versions" CASCADE;
DROP TABLE IF EXISTS "submissions" CASCADE;
DROP TABLE IF EXISTS "User" CASCADE;
DROP TABLE IF EXISTS "profiles" CASCADE;
DROP TABLE IF EXISTS "audit_logs" CASCADE;
DROP TYPE IF EXISTS "AppRole" CASCADE;
